version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          working_directory: react_extension
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          working_directory: react_extension
          name: "Install deps for test"
          command: yarn install
      - save_cache:
          working_directory: react_extension
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          working_directory: react_extension
          name: "Test"
          command: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
